function ai-sync --description "Fetch memini + litellm credentials from 1Password into a local cache"
    set -l CRED_FILE "$XDG_STATE_HOME/ai/credentials.fish"
    set -l tmp (mktemp)

    # label -> op reference. Read once here so no 1Password prompt fires on
    # every shell start / agent launch; re-run this after a key rotation.
    set -l NAMES MEMINI_API_KEY LITELLM_API_KEY
    set -l PATHS "op://Kubernetes/memini/MEMINI_API_KEY" "op://Kubernetes/litellm/LITELLM_MASTER_KEY"

    echo "# Generated by ai-sync — do not edit, do not commit." >"$tmp"

    for i in (seq (count $NAMES))
        set -l name $NAMES[$i]
        set -l ref $PATHS[$i]
        echo "Fetching $name from 1Password..."
        set -l value (op read "$ref" 2>/dev/null)
        if test -z "$value"
            echo "  ! could not read $ref — skipping" >&2
            continue
        end
        printf 'set -gx %s %s\n' $name (string escape -- "$value") >>"$tmp"
        set -gx $name "$value"
    end

    if test (count (string match -r '^set ' <"$tmp")) -eq 0
        echo "Error: nothing fetched — is `op` signed in?" >&2
        rm -f "$tmp"
        return 1
    end

    mkdir -p (dirname "$CRED_FILE")
    mv "$tmp" "$CRED_FILE"
    chmod 600 "$CRED_FILE"
    echo "Wrote $CRED_FILE (0600) and exported into this shell."
end
