[".config/spicetify/Themes/catppuccin"]
    type = "archive"
    url = "https://github.com/catppuccin/spicetify/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
